block.settings.custom_features_pipka:
  type: block_settings
  label: 'Pipka block'
  mapping:
    foo:
      type: string
      label: Foo

block.settings.custom_features_kipka:
  type: block_settings
  label: 'Kipka block'
  mapping:
    foo:
      type: string
      label: Foo

block.settings.custom_features_user:
  type: block_settings
  label: 'User block'
  mapping:
    foo:
      type: string
      label: Foo

block.settings.custom_features_lox:
  type: block_settings
  label: 'Lox block'
  mapping:
    foo:
      type: string
      label: Foo

# Schema for the configuration files of the Custom features module.
custom_features.settings:
  type: config_object
  label: 'Custom features settings'
  mapping:
    example:
      type: string
      label: 'Example'
